### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by stephenfin** [Colorsublime/Colorsublime-Plugin#2]
I'm getting errors when I attempt to get a list of themes:

```
Running install command.
Colorsublime: Urllib downloader failed: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "X/urllib/request.py", line 1252, in do_open
  File "X/http/client.py", line 1049, in request
  File "X/http/client.py", line 1087, in _send_request
  File "X/http/client.py", line 1045, in endheaders
  File "X/http/client.py", line 890, in _send_output
  File "X/http/client.py", line 828, in send
  File "X/http/client.py", line 1182, in connect
  File "X/socket.py", line 424, in create_connection
  File "X/socket.py", line 415, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "colorsublime.http.downloaders.urllib in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 26, in get
  File "X/urllib/request.py", line 160, in urlopen
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 491, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 1287, in https_open
  File "X/urllib/request.py", line 1255, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Colorsublime: 'bytes' object has no attribute 'getcode'
Traceback (most recent call last):
  File "colorsublime.http in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 33, in _run_downloader
  File "colorsublime.http.downloaders.urllib in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 36, in get_json
  File "colorsublime.http.downloaders.urllib in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 31, in get
AttributeError: 'bytes' object has no attribute 'getcode'
Colorsublime: Command execution error:
Traceback (most recent call last):
  File "colorsublime.async in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 43, in cb
  File "colorsublime.lib.concurrent.futures._base in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 397, in result
  File "colorsublime.lib.concurrent.futures._base in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 356, in __get_result
  File "colorsublime.lib.concurrent.futures.thread in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 72, in run
  File "colorsublime.commands in C:\Users\sfinucan\AppData\Roaming\Sublime Text 3\Installed Packages\Colorsublime.sublime-package", line 34, in fetch_theme_list
TypeError: 'bool' object is not iterable
Colorsublime: Theme list not found. Please check internet connection or enable debug in the settings and report the stack traces.
Colorsublime: ERROR: Theme list not found. Please check internet connection or enable debug in the settings and report the stack traces.
```

I suspect this is because I need to direct my traffic through a proxy. Therefore, I'd like to see proxy support added. I should note that this may already be present - I haven't looked very hard :) - but it doesn't appear to be easily configurable (i.e. via settings) if so.

PS: This also appears to show some other small bugs, like the `TypeError` one. I can open a new issue for these if you'd like.

PPS: Environment is:
* Windows 7 x64 (+ latest updates)
* Sublime Text 3 (latest version)

**Comment by improoviz** [comment]
Guys, just remove next folder:
C:\Users\USERNAME\AppData\Roaming\Sublime Text 3\Packages\Colorsublime - Themes\cache

It's gonna be ok, but this should be repeated every time.
P.S. Sorry for my english.

**Comment by pipplo** [comment]
I was able to get past the proxy with the latest version on windows.

I set an environment variable in windows https_proxy="my_proxy:port". After logging out and logging in everything was fine.

The key was setting https_proxy and not http_proxy since the repo url is an https url.

`
>>> urllib.request.getproxies()
{'http': 'myproxy:port', 'https': 'myproxy:port'}
`

**Comment by blopker** [comment]
Great. I'll add this to the README.

**Comment by pipplo** [comment]
Sorry to ping again, but I realized that instead of adding as a windows environment variable you can add it to the colorsublime settings file as well

{
	"https_proxy": "myproxy:port",
}

**Comment by MattGurneyAMP** [comment]
I had the same error as stephinfin.

My env:
ST3
Windows 7
Corporate Proxy which requires authentication

I fixed it by creating the following environment variable:
http_proxy=http://userid:password@proxyIpAddress:proxyPort

- userid: My windows userid
- password: my windows password
- proxyIpAddress: the address of our proxy, the dns name did not work
- proxyPort: Proxy Port

I restarted Sublime, but did not reboot to activate this.

I tried adding this setting to:
User settings for ColorSublime at 
C:\Users\myUserid\AppData\Roaming\Sublime Text 3\Packages\User\Colorsublime.sublime-settings

But it did not work
I also tried adding these type setting to that same file and they did not work:
- proxy_username
- proxy_password

It looks like the code for this plugin uses the python urllib library to access the list of themes, but does not use it's own property file to correctly set the proxy details. Anyway, the workaround from Windows environment variables worked for me.

I have so many proxy issues in so many applications, I just wish the error messages would tell you which Proxy values and source location the application is using, applications may be picking up settings from Windows, env vars, various property files etc.

**Comment by detly** [comment]
I have the same problem. This workplace has an NTLM authenticating proxy. On Linux I can use CNTLM and set environment variables to point to `localhost`. On Windows, running the Python snippet about returns `{}`.

I really, really don't want to put my domain credentials in plain text in an environment variable. Funnily enough, Package Control could **not** be installed via the one-liner, but once installed manually it **could** install Color Sublime itself.

**Comment by blopker** [comment]
Thanks for the info @detly. I haven't been impressed with the way proxies work in Python. There doesn't seems to be a 'one size fits all' solution. However, if someone does find one I'd implement it.

**Comment by detly** [comment]
@blopker A quick look at Package Control's issues showed [this comment](https://github.com/wbond/package_control/issues/361#issuecomment-20751160):

> The WinINet downloader piggy-backs off of your Windows/IE network connection, so none of the proxy stuff is necessary.

So it looks like on Windows they use a platform-specific library that automatically uses the OS's proxy settings (which most programs seem to do).

I understand the frustration!

**Comment by blopker** [comment]
I mostly just feel for people who have to deal with proxies... 

I took a look at PCs use of WinINet. It's a little intense: https://github.com/wbond/package_control/blob/890a05ff583264d3332cd288b4f60a7779b625e7/package_control/downloaders/wininet_downloader.py

I also found another implementation: https://github.com/saveenr/saveenr/blob/master/Demos/python/net_wininet_httpdownload.py 
But there's a lot of code smell in it so I don't know how much to trust it.

I have no Windows or proxy set up to test this stuff though. I'm not sure I'll make much headway.
