### ISSUE TITLE
Doesn't work on latest ST3

### ISSUE THREAD

**Issue by tobia** [Colorsublime/Colorsublime-Plugin#31]
ST3 build 3126 on Linux:

    reloading plugin Colorsublime.colorsublime-plugin
    Traceback (most recent call last):
      File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
        m = importlib.import_module(modulename)
      File "./python3.3/importlib/__init__.py", line 90, in import_module
      File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "colorsublime-plugin in /home/tobia/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 6, in <module>
      File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "colorsublime.commands in /home/tobia/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 16, in <module>
      File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "colorsublime.http in /home/tobia/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 6, in <module>
      File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "colorsublime.http.downloaders in /home/tobia/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 4, in <module>
      File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "colorsublime.http.downloaders.urllib in /home/tobia/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 5, in <module>
    ImportError: cannot import name error

**Comment by blopker** [comment]
Thank you for the report. I can't reproduce on OSX, but I'll check on my Linux install later tonight.

**Comment by ArchimedesPi** [comment]
Reproduced on ST3 build 3126 on Arch Linux:
```
reloading plugin Colorsublime.colorsublime-plugin
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "colorsublime-plugin in /home/liam/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 6, in <module>
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "colorsublime.commands in /home/liam/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 16, in <module>
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "colorsublime.http in /home/liam/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 6, in <module>
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "colorsublime.http.downloaders in /home/liam/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 4, in <module>
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "colorsublime.http.downloaders.urllib in /home/liam/.config/sublime-text-3/Installed Packages/Colorsublime.sublime-package", line 5, in <module>
ImportError: cannot import name error
```

**Comment by blopker** [comment]
I tried on my Ubuntu box and still couldn't reproduce. I'll try to get an Arch VM running next.

**Comment by blopker** [comment]
It's weird the plugin is trying to use the urllib downloader. Do either of you have curl or wget installed?

**Comment by ArchimedesPi** [comment]
I have both curl and wget installed.

Liam

**Comment by blopker** [comment]
@ArchimedesPi, when you get a chance can you run `from urllib import error` in your ST console? If that errors it means the Python packages that come with ST got corrupted somehow.

**Comment by ArchimedesPi** [comment]
Huh, odd. That errors out with this:
>>> from urllib import error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name error

Liam

**Comment by blopker** [comment]
It looks like the inclusion of Package Control broke something in newest ST: https://github.com/sergeche/emmet-sublime/issues/636 

Some people have had luck updating Package Control.

**Comment by tobia** [comment]
I was having the same error in Linux Mint 18 Cinnamon, and yes, `from urllib import error` was broken.

Thanks @blopker, following that procedure solved the issue:

1. Quit ST
2. Delete `~/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package`
3. Start ST

**Comment by blopker** [comment]
Hah, thanks everyone! Glad this got sorted.
