### ISSUE TITLE
Connection problem ?

### ISSUE THREAD

**Issue by alessandrobelli** [Colorsublime/Colorsublime-Plugin#32]
Hello!
I'm trying to run "install themes" but I get this error:
`ERROR:Colorsublime.colorsublime.status:Theme list not found. Please check internet connection or enable debug in settings and report the stack traces.
INFO:Colorsublime.colorsublime.status:ERROR: Theme list not found. Please check internet connection or enable debug in settings and report the stack traces.
Running install command.`

```
ERROR:Colorsublime.colorsublime.http:'bytes' object has no attribute 'getcode'
Traceback (most recent call last):
  File "colorsublime.http in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 23, in _run_downloader
  File "colorsublime.http.downloaders.urllib in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 33, in get
AttributeError: 'bytes' object has no attribute 'getcode'
ERROR:Colorsublime.colorsublime.async:Command execution error:
Traceback (most recent call last):
  File "colorsublime.async in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 43, in cb
  File "colorsublime.lib.concurrent.futures._base in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 397, in result
  File "colorsublime.lib.concurrent.futures._base in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 356, in __get_result
  File "colorsublime.lib.concurrent.futures.thread in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 72, in run
  File "colorsublime.commands in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 30, in fetch_repo
  File "colorsublime.io in C:\Users\abelli\Programs\Sublime Text Build 3103\Data\Installed Packages\Colorsublime.sublime-package", line 23, in extract
  File "./python3.3/tempfile.py", line 660, in write
```

My connection is working, other plugins are working correctly, what is my problem?
I checked this url in the settings:
` "repo_url": "https://github.com/Colorsublime/Colorsublime-Themes/archive/master.zip"
`
and it's working...

**Comment by blopker** [comment]
Thank you for the report.

What version OS and Sublime Text are you using?

**Comment by alessandrobelli** [comment]
@blopker 
Windows 7 service pack 1
Last stable version, build 3126

**Comment by blopker** [comment]
OK, thanks. I'll take a look when I can get a Windows VM up. It's odd that
it's trying to open a file called 'colorsublime.io'. It should be that zip
file. It's also weird your Sublime Text directory does not match the build
number you're running.

Other users has issues when an ST update corrupted their installs in subtle
ways. If it's not too much hassle I'd start with wiping ST and reinstalling.

**Comment by lijint** [comment]
same problem

**Comment by jarvisdev** [comment]
I faced the same issue. Please help.

**Comment by sergioestevess** [comment]
I’m having the same issue on MacOS 10.13.4 and ST 3.1.1 (build 3176)

**Comment by blopker** [comment]
Sorry to dig this up from the grave, but I saw that there was a coding error which was hiding the real reason this error was happening. That's been fixed, but the real issue probably hasn't. At least if it happens again the logs will show the real issue now (as of 2.1.1). Although if anyone one is on Mac or Linux, the package tries to use wget or curl first so installing either of those will likely resolve the issue as well.

**Comment by lijint** [comment]
我是李锦韬，已经收到你发的邮件了，我会及时查收的，谢谢
